version: 2
updates:
  - package-ecosystem: docker
    directory: images/build
    schedule:
      interval: weekly
    assignees:
      - VladyslavVolkov
    reviewers:
      - @bn-digital/sre
  - package-ecosystem: docker
    directory: images/openvpn
    schedule:
      interval: weekly
    assignees:
      - VladyslavVolkov
    reviewers:
      - @bn-digital/sre
  - package-ecosystem: docker
    directory: images/runtime
    schedule:
      interval: weekly
    assignees:
      - VladyslavVolkov
    reviewers:
      - @bn-digital/sre
  - package-ecosystem: docker
    directory: images/dind
    schedule:
      interval: weekly
    assignees:
      - VladyslavVolkov
    reviewers:
      - @bn-digital/sre
  - package-ecosystem: npm
    directory: images/build/app
    schedule:
      interval: weekly
    assignees:
      - VladyslavVolkov
    reviewers:
      - @bn-digital/sde
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: weekly
    assignees:
      - VladyslavVolkov
    reviewers:
      - @bn-digital/sre
