enableGlobalCache: true
nmHoistingLimits: workspaces
enableTelemetry: false
nodeLinker: node-modules
preferAggregateCacheInfo: false
logFilters:
  - code: YN0002
    level: discard
  - code: YN0007
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0013
    level: discard
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
yarnPath: .yarn/releases/yarn-3.0.2.cjs
