# nonk8s
apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: yarn
      context: images/build
      docker:
        target: default
    - image: nodejs
      context: images/runtime
      docker:
        target: nodejs
  tagPolicy:
    sha256: { }
  local:
    push: true
    useBuildkit: true

test:
  - image: yarn
    structureTests:
      - nodejs-container-structure-test.yaml
      - build-container-structure-test.yaml
  - image: nodejs
    structureTests:
      - nodejs-container-structure-test.yaml
      - runtime-container-structure-test.yaml

profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
      local:
        push: true
        useDockerCLI: true
        useBuildkit: true

