# nonk8s
apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    - image: yarn
      context: packages/yarn
      docker:
        pullParent: true
    - image: nodejs
      context: packages/nodejs
      docker:
        pullParent: true
    - image: dind
      context: packages/dind
      docker:
        pullParent: true
  tagPolicy:
    sha256: { }
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
test:
  - image: yarn
    structureTests:
      - nodejs-container-structure-test.yaml
      - build-container-structure-test.yaml
  - image: nodejs
    structureTests:
      - nodejs-container-structure-test.yaml
      - runtime-container-structure-test.yaml
profiles:
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
      local:
        useBuildkit: true
        push: true
