# nonk8s
apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
    - image: yarn
      context: images/build
      docker:
        target: default
    - image: nodejs
      context: images/runtime
      docker:
        target: nodejs
    - image: nginx
      context: images/runtime
      docker:
        target: static-nginx
    - image: php
      context: images/runtime
      docker:
        target: php-nginx
  tagPolicy:
    sha256: { }
  local:
    push: true
    useBuildkit: true
    concurrency: 0
profiles:
  - name: release
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
      local:
        push: true
        useDockerCLI: true
        useBuildkit: true
