# nonk8s
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: yarn
      context: packages/yarn
    - image: openvpn
      context: packages/openvpn
    - image: nodejs
      context: packages/nodejs
    - image: dind
      context: packages/dind
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
    useBuildkit: true
test:
  - image: yarn
    structureTests:
      - nodejs-container-structure-test.yaml
      - build-container-structure-test.yaml
  - image: nodejs
    structureTests:
      - nodejs-container-structure-test.yaml
      - runtime-container-structure-test.yaml
profiles:
  - name: staging
    activation:
      - env: CI=true
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
      local:
        push: true
