# nonk8s
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: yarn
      context: images/build
    - image: html
      context: images/runtime
      docker:
        target: html
    - image: php
      context: images/runtime
      docker:
        target: php
    - image: nodejs
      context: images/runtime
      docker:
        target: nodejs
  tagPolicy:
    sha256: { }
  local:
    push: false
    useBuildkit: true
    concurrency: 0
profiles:
  - name: release
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
      local:
        push: true
        useBuildkit: true
        concurrency: 0
