# nonk8s
apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
    - image: yarn
      context: images/build
    - image: nodejs
      context: images/runtime
      docker:
        target: nodejs
    - image: nginx
      context: images/runtime
      docker:
        target: nodejs-nginx
    - image: react
      context: images/runtime
      docker:
        target: react
    - image: strapi
      context: images/runtime
      docker:
        target: strapi
    - image: php
      context: images/runtime
      docker:
        target: php-nginx
    - image: openvpn
      context: images/openvpn
  tagPolicy:
    sha256: { }
  local:
    push: true
    useBuildkit: true
    concurrency: 0
profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
      local:
        push: true
        useBuildkit: true
        concurrency: 0
