# nonk8s
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: yarn
      context: images/build
      docker:
        target: yarn
    - image: openvpn
      context: images/openvpn
    - image: nodejs
      context: images/runtime
      docker:
        target: nodejs
    - image: dind
      context: images/dind
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
    useBuildkit: true
test:
  - image: yarn
    structureTests:
      - nodejs-container-structure-test.yaml
      - build-container-structure-test.yaml
  - image: nodejs
    structureTests:
      - nodejs-container-structure-test.yaml
      - runtime-container-structure-test.yaml
profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
      local:
        push: true
