apps:
  - cwd: /usr/local/src
    script: bin/app.js
    env:
      STRAPI_DISABLE_UPDATE_NOTIFICATION: 'true'
      STRAPI_HIDE_STARTUP_MESSAGE: 'true'
      STRAPI_TELEMETRY_DISABLED: 'true'
      BROWSER: 'false'
    watch: false
    instances: 1
    source_map_support: true
    exec_mode: cluster
    name: app
