compressionLevel: 0

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard

nmHoistingLimits: workspaces

nmSelfReferences: false

nodeLinker: node-modules

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.25.cjs
