enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard

nmHoistingLimits: workspaces

nmSelfReferences: false

nmMode: hardlinks-global

nodeLinker: node-modules

preferAggregateCacheInfo: true

compressionLevel: 0

yarnPath: .yarn/releases/yarn-4.0.0-rc.24.cjs
