enableGlobalCache: true
enableTelemetry: false
cacheFolder: /var/cache/yarn
nmHoistingLimits: workspaces
nmMode: classic
nodeLinker: node-modules
preferAggregateCacheInfo: true
yarnPath: .yarn/releases/yarn-4.0.0-rc.40.cjs
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard
