# nonk8s
apiVersion: skaffold/v3beta4
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: cms
      docker:
        target: cms
    - image: website
      docker:
        target: website
profiles:
  - name: staging
    build:
      tagPolicy:
        sha256: {}
  - name: production
    build:
      local:
        push: true
        tryImportMissing: true
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
