on:
  workflow_call:
    inputs:
      environment:
        required: false
        description: Used by Skaffold and Helmfile profiles
        type: string
        default: staging

env:
  APP_NAME: ${{ github.event.repository.name }}
  APP_ENV: ${{ inputs.environment }}

concurrency:
  group: ${{ github.event.repository.name }}-docker-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Generate cms .env files
        uses: bn-digital/vault-env@latest
        continue-on-error: true
        with:
          endpoint: ${{ secrets.VAULT_ENDPOINT }}
          token: ${{ secrets.GH_TOKEN }}
          template: packages/cms/.env.${{ env.APP_ENV }}
          target: packages/cms/.env

      - name: Generate website .env files
        uses: bn-digital/vault-env@latest
        continue-on-error: true
        with:
          endpoint: ${{ secrets.VAULT_ENDPOINT }}
          token: ${{ secrets.GH_TOKEN }}
          template: packages/website/.env.${{ env.APP_ENV }}
          target: packages/website/.env.production

      - name: Login Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}/${{ env.APP_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          command: build
          skip-tests: false
          repository: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}
          profile: ${{ env.APP_ENV }}
#
#      - name: Install Cosign
#        uses: sigstore/cosign-installer@v2.0.0
#
#      - name: Sign image
#        run: |
#          echo ${COSIGN_KEY} > /tmp/my_cosign.key && \
#          cosign sign --key /tmp/my_cosign.key ${TAGS}
#        env:
#          TAGS: ${{ steps.docker_meta.outputs.tags }}
#          COSIGN_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
#          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

