name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ secrets.VAULT_PUBLIC_URL }}
          githubToken: ${{ github.token }}
          secrets: |
            infrastructure/data/harbor registry | DOCKER_REGISTRY ;
            infrastructure/data/harbor username | DOCKER_USERNAME ;
            infrastructure/data/harbor password | DOCKER_PASSWORD ;

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}/library
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.15.0
        with:
          command: build
          profile: release
          repository: ${{ env.DOCKER_REGISTRY }}/library
