name: Release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.3.1
        id: secrets
        with:
          method: github
          url: ${{ secrets.vault_endpoint }}
          githubToken: ${{ secrets.gh_token }}
          secrets: |
            infrastructure/data/bndigital/staging/registry docker-url | docker_url ;
            infrastructure/data/bndigital/staging/registry docker-username | docker_username ;
            infrastructure/data/bndigital/staging/registry docker-password | docker_password ;

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.secrets.outputs.docker_url }}
          username: ${{ steps.secrets.outputs.docker_username }}
          password: ${{ steps.secrets.outputs.docker_password }}

      - name: Build Docker images
        uses: hiberbee/github-action-pipelines@1.14.0
        with:
          command: build
          profile: release
          repository: ${{ steps.secrets.outputs.docker_url }}/library
