on:
  workflow_call:
    inputs:
      environment:
        required: false
        description: Used by Skaffold and Helmfile profiles
        type: string
        default: staging

env:
  APP_NAME: ${{ github.event.repository.name }}
  APP_ENV: ${{ inputs.environment }}

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}/${{ env.APP_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test Docker images
        uses: hiberbee/github-action-skaffold@1.21.0
        with:
          command: test
          images: ${{ secrets.DOCKER_REGISTRY }}/${{ env.APP_NAME }}/cms:latest,${{ secrets.DOCKER_REGISTRY }}/${{ env.APP_NAME }}/website:latest
          profile: ${{ env.APP_ENV }}
